export const filterTypes = {
  SET_FILTER_ORIGINS: 'SET_FILTER_ORIGINS',
  SET_FILTER_MIN_PRICE: 'SET_FILTER_MIN_PRICE',
  SET_FILTER_MAX_PRICE: 'SET_FILTER_MAX_PRICE',
  SET_FILTER_PAGINATION: 'SET_FILTER_PAGINATION',
  SET_FILTERS: 'SET_FILTERS',
};